### ISSUE TITLE
Distributed artifact should not be named commandline-x.x.x.zip

### ISSUE THREAD

**Issue by DirkMahler** [buschmais/jqa-commandline-tool#10]
The ZIP archive should carry jqassistant in it's name to make it easier locating it in user's Downloads/ folders with many other archives.

**Comment by obfischer** [comment]
It is already on the list of things for the next release. I have seen the tweet. ;-)

**Comment by DirkMahler** [comment]
Ok ;.)

**Comment by obfischer** [comment]
The name of the commandline distribution will be `jqassistant-commandline-1.3.0.zip`.

**Comment by obfischer** [comment]
Last commit contains also an entry for this for the release notes.
