### ISSUE TITLE
Incorrect Documentation for --uris

### ISSUE THREAD

**Issue by naraesk** [buschmais/jqa-commandline-tool#13]
According to https://buschmais.github.io/jqassistant/doc/1.6.0/#cli:scan the long form of the command line option ```-u``` is ```--urls```

According to executing ```jqassistant -help```  the option is ```--uris``` (i instead of l), which seems to be the correct one

**Comment by DirkMahler** [comment]
The issue is fixed, the option has been renamed to --urls (which semantically is better) and will be available with the next release.
