### ISSUE TITLE
Unable to build : Could not find artifact com.buschmais.jqassistant:commandline:zip:distribution:1.2.0-SNAPSHOT

### ISSUE THREAD

**Issue by nmervaillie** [buschmais/jqa-commandline-tool#2]
Building the module gives me the following error :
```[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:unpack (unpack-test-distribution) on project commandline: Unable to find artifact. Could not find artifact com.buschmais.jqassistant:commandline:zip:distribution:1.2.0-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots)```

I guess this is due to the integration tests that try to download the zip distribution, which are built later on the pipeline.

Details of the commands I used to build :
```
cd jqa-uber-parent && mvn clean install
cd ../jqa-core-framework && mvn clean install
cd ../jqa-asciidoctor-utilities && mvn clean install
cd ../jqa-plugin-parent && mvn clean install
cd ../jqa-plugin-common && mvn clean install
cd ../jqa-java-plugin && mvn clean install
cd ../jqa-junit-plugin && mvn clean install
cd ../jqa-xml-plugin && mvn clean install
cd ../jqa-yaml-plugin && mvn clean install
cd ../jqa-commandline-tool && mvn clean install
```

**Comment by obfischer** [comment]
BTW, you don't need to build all projects by yourself if it is fine for you to use our nightly snapshots. Simply add the following repository to your `settings.xml`.

```xml
<repository>
  <snapshots>
    <enabled>true</enabled>
  </snapshots>
  <id>sonatype-nexus-snapshots</id>
  <name>Sonatype Nexus Snapshots</name>
  <url>https://oss.sonatype.org/content/repositories/snapshots</url>
</repository>
```

**Comment by obfischer** [comment]
We will add this repository definition to all jQAssistant projects. This will possible contributors help to get started with jQAssistant. 

So your issues was very helpful in many ways.
